# questions.toml

[easy]
label = "Easy Mode"

[[easy.questions]]
question = "What does 'HTML' stand for? "
answers = ["hypertext markup language"]
alternatives = [
    "hypertitle makeup language",
    "hyper text markup language"
]

[[easy.questions]]
question = "Which built-in function can get information from the user?"
answers = ["input"]
alternatives = [
    "get", 
    "print", 
    "write"
]

[[easy.questions]]
question = "What does 'CSS' stand for?"
answers = ["Cascading style sheets"]
alternatives = [
    "Cascading sheets style",
    "Control sample styles",
    "Contact style sheets",
]

[[easy.questions]]
question = "What was the name of the first programing language?"
answers = ["Algorithm for the analytical Engine"]
alternatives = [
    "HTML", 
    "Javascript", 
    "Fortran"
]

[[easy.questions]]
question = "What is CSS used for?"
answers = ["Style the code"]
alternatives = [
    "Auto correct",
    "Change the codes structure",
    "Closes the code",
]

[[easy.questions]]
question = "HTML and CSS workes very good togheter?"
answers = ["True"]
alternatives = [
    "False",
]

[[easy.questions]]
question = "How can you run a Python script named quiz.py"
answers = ["python quiz.py", "python -m quiz"]
alternatives = ["python quiz", "python -m quiz.py"]

[[easy.questions]]
question = "What is the diffrent between and 'UL' and 'OL' in HTML?"
answers = [
    "UL is an unorderd list and OL is an orderd list",
]
alternatives = [
    "There is no diffrence",
    "UL stands for underline and OL stands for overline",
]

[normal]
label = "Normal Mode"

[[normal.questions]]
question = "Which version of Python is the first with TOML support built in"
answers = ["3.11"]
alternatives = [
    "3.9", 
    "3.10", 
    "3.12"
]

[hard]
label = "Hard Mode"

[[hard.questions]]
question = "Best language to use for developing a website"
answers = ["HTML"]
alternatives = [
    "Javascript", 
    "CSS", 
    "Python"
]

[[hard.questions]]
question = "When was the first public version of Python released"
answers = ["February 1991"]
alternatives = [
    "January 1994", 
    "October 2000", 
    "December 2008"
]

[[hard.questions]]
question = "What's a PEP"
answers = ["A Python Enhancement Proposal"]
alternatives = [
    "A Pretty Exciting Policy",
    "A Preciously Evolved Python",
    "A Potentially Epic Prize",
]